version: "3"

services:
  resume-backend:
    image: your-registry/resume-backend-keystone:latest
    container_name: your-container-name
    # platform: linux/amd64
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - SESSION_SECRET=
      - ALLOW_ORIGINS=http://localhost:3000;http://localhost:4000
      - DB_FILEPATH=./keystone.db
      - S3_BUCKET_NAME=
      - S3_REGION=
      - S3_ACCESS_KEY_ID=
      - S3_SECRET_ACCESS_KEY=
      - S3_ENDPOINT=
      - TZ=Asia/Seoul
    volumes:
      - "./path/to/dbfile:/usr/src/app/keystone.db"
    network_mode: bridge
